**21022008_NguyenHuuTho**

In [ ]:
import numpy as np
from numpy import *

In [ ]:
# Activation function
def sigmoid(t):
    return 1/(1+np.exp(-t))

# Derivative of sigmoid
def sigmoid_derivative(p):
    return p * (1 - p)

In [ ]:
class NeuralNetwork:
    def __init__(self, x,y):
        self.input = x
        self.weights1= np.random.rand(self.input.shape[1],4) # considering we have 4 nodes in the hidden layer
        self.weights2 = np.random.rand(4,1)
        self.y = y
        self.output = np. zeros(y.shape)
        
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.layer2 = sigmoid(np.dot(self.layer1, self.weights2))
        return self.layer2
        
    def backprop(self):
        d_weights2 = np.dot(self.layer1.T, 2*(self.y -self.output)*sigmoid_derivative(self.output))
        d_weights1 = np.dot(self.input.T, np.dot(2*(self.y -self.output)*sigmoid_derivative(self.output), self.weights2.T)*sigmoid_derivative(self.layer1))
    
        self.weights1 += d_weights1
        self.weights2 += d_weights2

    def train(self, X, y):
        self.output = self.feedforward()
        self.backprop()

In [ ]:
X=np.array(([0,0,1,1],[0,1,0,1],[1,1,1,1],[0,1,1,0]), dtype=float)
y=np.array(([0],[1],[1],[0]), dtype=float)

NN = NeuralNetwork(X,y)
for i in range(1500): # trains the NN 1,000 times
    if i % 100 ==0: 
        print ("for iteration # " + str(i) + "\n")
        print ("Input : \n" + str(X))
        print ("Actual Output: \n" + str(y))
        print ("Predicted Output: \n" + str(NN.feedforward()))
        print ("Loss: \n" + str(np.mean(np.square(y - NN.feedforward())))) # mean sum squared loss
        print ("\n")
    NN.train(X, y)

for iteration # 0

Input : 
[[0. 0. 1. 1.]
 [0. 1. 0. 1.]
 [1. 1. 1. 1.]
 [0. 1. 1. 0.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.81294637]
 [0.83662675]
 [0.86722552]
 [0.82945865]]
Loss: 
0.3483008334709272


for iteration # 100

Input : 
[[0. 0. 1. 1.]
 [0. 1. 0. 1.]
 [1. 1. 1. 1.]
 [0. 1. 1. 0.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.08314431]
 [0.98223273]
 [0.9091063 ]
 [0.08456662]]
Loss: 
0.005660457725713554


for iteration # 200

Input : 
[[0. 0. 1. 1.]
 [0. 1. 0. 1.]
 [1. 1. 1. 1.]
 [0. 1. 1. 0.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.04262649]
 [0.99019673]
 [0.96012712]
 [0.04234379]]
Loss: 
0.0013239914318842626


for iteration # 300

Input : 
[[0. 0. 1. 1.]
 [0. 1. 0. 1.]
 [1. 1. 1. 1.]
 [0. 1. 1. 0.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.03064735]
 [0.99156674]
 [0.97207846]
 [0.03010016]]
Loss: 
0.0006740029282290386


for iteration # 400

Input : 
[[0. 0. 1. 1.]
 [0. 