In [3]:
import numpy as np
from numpy import *

In [4]:
# Activation function
def sigmoid(t):
    return 1/(1+np.exp(-t))

# Derivative of sigmoid
def sigmoid_derivative(p):
    return p * (1 - p)

In [5]:
class NeuralNetwork:
    def __init__(self, x,y):
        self.input = x
        self.weights1= np.random.rand(self.input.shape[1],4) # considering we have 4 nodes in the hidden layer
        self.weights2 = np.random.rand(4,1)
        self.y = y
        self.output = np. zeros(y.shape)

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.layer2 = sigmoid(np.dot(self.layer1, self.weights2))
        return self.layer2

    def backprop(self):
        d_weights2 = np.dot(self.layer1.T, 2*(self.y -self.output)*sigmoid_derivative(self.output))
        d_weights1 = np.dot(self.input.T, np.dot(2*(self.y -self.output)*sigmoid_derivative(self.output), self.weights2.T)*sigmoid_derivative(self.layer1))

        self.weights1 += d_weights1
        self.weights2 += d_weights2

    def train(self, X, y):
        self.output = self.feedforward()
        self.backprop()

In [6]:
X=np.array(([1,1,1],[1,1,0],[0,0,0],[1,1,0]), dtype=float)
y=np.array(([1],[0],[1],[1]), dtype=float)

NN = NeuralNetwork(X,y)
for i in range(1500): # trains the NN 1,000 times
    if i % 100 ==0:
        print ("for iteration # " + str(i) + "\n")
        print ("Input : \n" + str(X))
        print ("Actual Output: \n" + str(y))
        print ("Predicted Output: \n" + str(NN.feedforward()))
        print ("Loss: \n" + str(np.mean(np.square(y - NN.feedforward())))) # mean sum squared loss
        print ("\n")
    NN.train(X, y)

for iteration # 0

Input : 
[[1. 1. 1.]
 [1. 1. 0.]
 [0. 0. 0.]
 [1. 1. 0.]]
Actual Output: 
[[1.]
 [0.]
 [1.]
 [1.]]
Predicted Output: 
[[0.8655342 ]
 [0.8520121 ]
 [0.75044102]
 [0.8520121 ]]
Loss: 
0.2070464437603952


for iteration # 100

Input : 
[[1. 1. 1.]
 [1. 1. 0.]
 [0. 0. 0.]
 [1. 1. 0.]]
Actual Output: 
[[1.]
 [0.]
 [1.]
 [1.]]
Predicted Output: 
[[0.91190622]
 [0.52967788]
 [0.89562049]
 [0.52967788]]
Loss: 
0.13010428730211557


for iteration # 200

Input : 
[[1. 1. 1.]
 [1. 1. 0.]
 [0. 0. 0.]
 [1. 1. 0.]]
Actual Output: 
[[1.]
 [0.]
 [1.]
 [1.]]
Predicted Output: 
[[0.96346478]
 [0.50658364]
 [0.94245459]
 [0.50658364]]
Loss: 
0.12618324621466065


for iteration # 300

Input : 
[[1. 1. 1.]
 [1. 1. 0.]
 [0. 0. 0.]
 [1. 1. 0.]]
Actual Output: 
[[1.]
 [0.]
 [1.]
 [1.]]
Predicted Output: 
[[0.97525623]
 [0.5034059 ]
 [0.95646645]
 [0.5034059 ]]
Loss: 
0.1256326561318297


for iteration # 400

Input : 
[[1. 1. 1.]
 [1. 1. 0.]
 [0. 0. 0.]
 [1. 1. 0.]]
Actual Output: 
[[1.]
 [0