**import thư viện**

In [ ]:
import numpy as np
from numpy import *

**Xây dựng hàm sigmoid**

In [ ]:
# Activation function
def sigmoid(t):
    return 1/(1+np.exp(-t))

# Derivative of sigmoid
def sigmoid_derivative(p):
    return p * (1 - p)

**Xây dựng class NeuralNet**

In [ ]:
class NeuralNetwork:
    def __init__(self, x,y):
        self.input = x
        self.weights1= np.random.rand(self.input.shape[1],4) # considering we have 4 nodes in the hidden layer
        self.weights2 = np.random.rand(4,1)
        self.y = y
        self.output = np. zeros(y.shape)
        
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.layer2 = sigmoid(np.dot(self.layer1, self.weights2))
        return self.layer2
        
    def backprop(self):
        d_weights2 = np.dot(self.layer1.T, 2*(self.y -self.output)*sigmoid_derivative(self.output))
        d_weights1 = np.dot(self.input.T, np.dot(2*(self.y -self.output)*sigmoid_derivative(self.output), self.weights2.T)*sigmoid_derivative(self.layer1))
    
        self.weights1 += d_weights1
        self.weights2 += d_weights2

    def train(self, X, y):
        self.output = self.feedforward()
        self.backprop()

**Triển khai mạng Neural**

In [ ]:
X=np.array(([1,1,1],[1,1,0],[0,0,0],[1,1,0]), dtype=float)
y=np.array(([1],[0],[1],[1]), dtype=float)

NN = NeuralNetwork(X,y)
for i in range(1500): # trains the NN 1,000 times
    if i % 100 ==0: 
        print ("for iteration # " + str(i) + "\n")
        print ("Input : \n" + str(X))
        print ("Actual Output: \n" + str(y))
        print ("Predicted Output: \n" + str(NN.feedforward()))
        print ("Loss: \n" + str(np.mean(np.square(y - NN.feedforward())))) # mean sum squared loss
        print ("\n")
    NN.train(X, y)

for iteration # 0

Input : 
[[1. 1. 1.]
 [1. 1. 0.]
 [0. 0. 0.]
 [1. 1. 0.]]
Actual Output: 
[[1.]
 [0.]
 [1.]
 [1.]]
Predicted Output: 
[[0.83788035]
 [0.81749867]
 [0.72767504]
 [0.81749867]]
Loss: 
0.2005136171905912


for iteration # 100

Input : 
[[1. 1. 1.]
 [1. 1. 0.]
 [0. 0. 0.]
 [1. 1. 0.]]
Actual Output: 
[[1.]
 [0.]
 [1.]
 [1.]]
Predicted Output: 
[[0.88738361]
 [0.55618586]
 [0.88404431]
 [0.55618586]]
Loss: 
0.1331104685005597


for iteration # 200

Input : 
[[1. 1. 1.]
 [1. 1. 0.]
 [0. 0. 0.]
 [1. 1. 0.]]
Actual Output: 
[[1.]
 [0.]
 [1.]
 [1.]]
Predicted Output: 
[[0.96101832]
 [0.50775152]
 [0.9443453 ]
 [0.50775152]]
Loss: 
0.1261842971514826


for iteration # 300

Input : 
[[1. 1. 1.]
 [1. 1. 0.]
 [0. 0. 0.]
 [1. 1. 0.]]
Actual Output: 
[[1.]
 [0.]
 [1.]
 [1.]]
Predicted Output: 
[[0.97500356]
 [0.50348638]
 [0.9594659 ]
 [0.50348638]]
Loss: 
0.12557303629872962


for iteration # 400

Input : 
[[1. 1. 1.]
 [1. 1. 0.]
 [0. 0. 0.]
 [1. 1. 0.]]
Actual Output: 
[[1.]
 [0.