In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report

**Tải dữ liệu**

In [ ]:
penguins = pd.read_csv('/content/drive/MyDrive/TH1391_NLMH/Week10_Thuchanh4/penguins.csv')
penguins

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    MALE  
1         3800.0  FEMALE  
2         3250.0  FEMALE  
3            NaN     NaN  
4         3450.0  FEMALE  
..           ...     ...  
339          NaN     NaN  
340       4850.0  FEMALE  
341       5750.0    MALE  
342       5200.0  FEMALE  
343       5400.0    MALE  

[344 rows x 7 columns]

**Tiền xử lý dữ liệu**

Bạn cần xác định xem cột nào sẽ được sử dụng làm đặc trưng và cột nào sẽ là nhãn mục tiêu.

Giả sử chúng ta sử dụng tất cả các cột số và mục tiêu của chúng ta là một cột hạng mục, chúng ta có thể làm như sau:

In [ ]:
features = penguins.select_dtypes(include=[np.number])
target = penguins['species']  # replace 'species' with your actual target column

# Convert target to numerical
le = LabelEncoder()
target = le.fit_transform(target)

In [ ]:
# Fill NaN values with mean of the respective column
features = features.fillna(features.mean())

**Tách dữ liệu**

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

**Khởi tạo và huấn luyện mô hình**

In [ ]:
knn = KNeighborsClassifier(n_neighbors=5, p=2)
knn.fit(X_train, y_train)

KNeighborsClassifier()

**Dự đoán và đánh giá**

In [ ]:
y_pred = knn.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Visualization
sns.scatterplot(data=X_test, hue=y_pred)
plt.show()

[[25  2  5]
 [13  3  0]
 [ 1  1 19]]
              precision    recall  f1-score   support

           0       0.64      0.78      0.70        32
           1       0.50      0.19      0.27        16
           2       0.79      0.90      0.84        21

    accuracy                           0.68        69
   macro avg       0.64      0.62      0.61        69
weighted avg       0.65      0.68      0.65        69



ValueError: ignored

In [14]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.impute import SimpleImputer

# Tải dữ liệu
penguins = pd.read_csv('/content/drive/MyDrive/TH1391_NLMH/Week10_Thuchanh4/penguins.csv')

# Drop rows where target is NaN
penguins = penguins.dropna(subset=['species'])  # replace 'species' with your actual target column

# Tiền xử lý dữ liệu
features = penguins.select_dtypes(include=[np.number])
target = penguins['species']  # replace 'species' with your actual target column

# Fill NaN values with mean of the respective column
imputer = SimpleImputer(strategy='mean')
features = imputer.fit_transform(features)

# Convert target to numerical
le = LabelEncoder()
target = le.fit_transform(target)

# Tách dữ liệu
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

# Khởi tạo và huấn luyện mô hình
knn = KNeighborsClassifier(n_neighbors=5, p=2)
knn.fit(X_train, y_train)

# Dự đoán và đánh giá
y_pred = knn.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[25  2  5]
 [13  3  0]
 [ 1  1 19]]
              precision    recall  f1-score   support

           0       0.64      0.78      0.70        32
           1       0.50      0.19      0.27        16
           2       0.79      0.90      0.84        21

    accuracy                           0.68        69
   macro avg       0.64      0.62      0.61        69
weighted avg       0.65      0.68      0.65        69

